name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore *.slnx

      - name: Build
        run: dotnet build *.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test *.slnx --configuration Release --no-build --verbosity normal

      - name: Pack
        run: |
            dotnet pack Test.Core.csproj \
            --configuration Release \
            --no-build \
            --output ./artifacts

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: Test.Core.Package
          path: ./artifacts/*.nupkg